=== GabrieleMaurina/advanced_dbms_golf_project/GolfScore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Golfscore">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
							<xs:attribute name="Id" type="xs:string" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element> 
				<xs:element name="Date" type="xs:date"/>
				<xs:element name="Player" type="xs:string"/>
				<xs:element name="Results">
				   <xs:complexType>
						<xs:sequence>
							<xs:element name="Hole" type="holeT" minOccurs="0" maxOccurs="9"/>
							<xs:element name="Withdraw" minOccurs="0">
								<xs:complexType>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
   <xs:complexType name= "holeT">
     <xs:simpleContent>
       <xs:extension base="holeResultT">
         <xs:attribute name="Number" type="holeNumberT" />
		 <xs:attribute name="par" type="holeParT" />
		 <xs:attribute name="difficulty" type="holeNumberT" />
       </xs:extension>
     </xs:simpleContent>
   </xs:complexType>
	<xs:simpleType name="holeNumberT">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="9"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="holeParT">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="5"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="holeResultT">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="8"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== GabrieleMaurina/advanced_dbms_golf_project/GolfScore.xml
<?xml version="1.0" encoding="UTF-8"?>
<Golfscore xsi:noNamespaceSchemaLocation="Golfscore.xsd" 
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Name Id="324">President's Cup</Name>
	<Player>FC1001</Player>
	<Results>
		<Hole Number="1" par="3" difficulty="9">3</Hole> 
		<Hole Number="2" par="4" difficulty="3">5</Hole> 
		<Hole Number="3" par="4" difficulty="4">4</Hole>
		<Hole Number="4" par="5" difficulty="2">6</Hole> 
		<Hole Number="5" par="3" difficulty="7">4</Hole>
		<Hole Number="6" par="4" difficulty="8">5</Hole> 
		<Hole Number="7" par="4" difficulty="6">4</Hole>
		<Hole Number="8" par="5" difficulty="1">3</Hole> 
		<Hole Number="9" par="3" difficulty="5">4</Hole>
	</Results>
</Golfscore>
